# Generated by Django 5.0.3 on 2024-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_res', models.ImageField(upload_to='low_res/')),
                ('high_res', models.ImageField(blank=True, null=True, upload_to='high_res/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
